---
title: "PPCR 2026 Project 2 Quarto"
format:
  html:
    page-layout: full
editor: visual
execute:
  echo: false
  warning: false
---

```{r}
#| title: Loading libraries

library(tidyverse)
library(haven)
library(psych)
library(skimr)
library(gt)
library(patchwork)

```

```{r}
#| title: Building full data sample


library(tidyverse)
library(haven)
library(psych)
library(skimr)
library(GGally)

#Loading raw data

demographics_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/DEMO_L.xpt")
depression_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/DPQ_L.xpt")
diabetes_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/DIQ_L.xpt")
pa_sitting_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/PAQ_L.xpt")
smoking_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/SMQ_L.xpt")
alcohol_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/ALQ_L.xpt")
unemployment_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/OCQ_L.xpt")
bloodpressure_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/BPXO_L.xpt")
bpcholesterol_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/BPQ_L.xpt")
comorbidities_raw <- read_xpt("G:/My Drive/PPCR/Project 2/NHANES Data/MCQ_L.xpt")

#Joining the raw data into a single dataframe

nhanes_project_2_raw <- demographics_raw |> 
  full_join(pa_sitting_raw, by = "SEQN") |> 
  full_join(depression_raw, by = "SEQN") |> 
  full_join(diabetes_raw, by = "SEQN") |> 
  full_join(smoking_raw, by = "SEQN") |>
  full_join(alcohol_raw, by = "SEQN") |> 
  full_join(unemployment_raw, by = "SEQN") |> 
  full_join(bloodpressure_raw, by = "SEQN") |> 
  full_join(bpcholesterol_raw, by = "SEQN") |> 
  full_join(comorbidities_raw, by = "SEQN") |> 
  zap_labels()


#Defining "refused" and "dont know"

depression_refused_dunno <- c(7, 9)
pa_refused_or_dunno <- c(7777, 9999)
smoking_refused_or_dunno <- c(7, 9)
alcohol_small_refused_or_dunno <- c(7, 9)
alcohol_medium_refused_or_dunno <- c(77, 99)
alcohol_large_refused_or_dunno <- c(777, 999)
diabetes_refused_or_dunno <- c(7, 9)
bpcholesterol_refused_or_dunno <- c(7, 9)
comorbidities_refused_or_dunno <- c(7, 77, 9, 99)
OCD150_refused_or_dunno <- c(7, 9)
OCQ383_refused_or_dunno <- c(77, 99)


#Cleaning the data

nhanes_project_2 <- nhanes_project_2_raw |> 
  
  #Selecting variables of interest
  select(
    #Demographics variables
    SEQN, RIAGENDR, RIDAGEYR, RIDRETH3, INDFMPIR, WTINT2YR, WTMEC2YR, SDMVPSU, SDMVSTRA,
    #depression variables
    c(DPQ010:DPQ100), 
    #Physical activity and sitting variables
    c(PAD790Q:PAD680),
    #Smoking variables
    SMQ020, SMQ040,
    #Alcohol use variables
    ALQ111, ALQ121, ALQ130,
    #Unemployment variables
    OCD150, OCQ383,
    #Diabetes variables
    DIQ010, DIQ160, DIQ050, DIQ070,
    #Blood pressure variables
    BPXOSY1, BPXOSY2, BPXOSY3, BPXODI1, BPXODI2, BPXODI3, BPQ020, BPQ030, BPQ150,
    #Cholesterol variables
    BPQ080, BPQ101D,
    #Comorbidities variables
    MCQ010, MCQ035, MCQ040, MCQ050, MCQ160A, MCQ160B, MCQ160C, MCQ160D, MCQ160E, MCQ160F, MCQ160M, MCQ170M, MCQ160P, MCQ160L, MCQ170L, MCQ220
  ) |>
  
  #Demographics data cleaning
  
  #Renaming variables
  rename(Gender = RIAGENDR,
         Age = RIDAGEYR,
         Race = RIDRETH3,
         Ratio_income_poverty = INDFMPIR
  ) |>
  #Setting values for gender (Male = 1, Female = 0)
  mutate(Gender = if_else(Gender == 1, 1, 0)) |> 
  #Setting values for Race 
  #(Non-Hispanic White = 0, Mexican American = 1, Other Hispanic  = 2, Non-Hispanic Black = 3,
  #Non-Hispanic Asian = 4, Other Race - Including Multi-Racial = 5)
  mutate(Race = case_when(Race == 1 ~ 1,
                          Race == 2 ~ 2,
                          Race == 3 ~ 0,
                          Race == 4 ~ 3,
                          Race == 6 ~ 4,
                          Race == 7 ~ 5)
  ) |> 
  
  #Depression data cleaning
  
  #Calculating PHQ-9 Score
  mutate(across(c(DPQ010:DPQ090), ~ replace_values(.x, depression_refused_dunno ~ NA))) |> 
  mutate(PHQ9_Score = rowSums(across(DPQ010:DPQ090), na.rm = FALSE)) |> 
  #Categorizing depression yes/no (score >= 10)
  mutate(depression = if_else(PHQ9_Score >= 10, 1, 0)) |> 
  
  #Physical activity data cleaning
  
  #Setting factor variables as factors
  mutate(PAD790U = as.factor(PAD790U),
         PAD810U = as.factor(PAD810U)) |> 
  #Setting "refused", "dont know" or "0" as missing
  mutate(across(c(PAD790Q, PAD800, PAD810Q, PAD820, PAD680), ~ replace_values(.x, pa_refused_or_dunno ~ NA))) |> 

  #Renaming sitting time
  rename("sitting_time" = "PAD680") |>
  #Transforming observation data to minutes_per_week of moderate activity
  mutate(moderate_weekly_minutes = case_when(
    PAD790U == "D" ~ PAD800 * PAD790Q * 7,
    PAD790U == "M" ~ (PAD800 * PAD790Q) / 4,
    PAD790U == "Y" ~ (PAD800 * PAD790Q) / 52,
    PAD790U == "W" ~ PAD800 * PAD790Q)
  ) |> 
  mutate(moderate_weekly_minutes = round(moderate_weekly_minutes, digits = 0)) |> 
  #calculating weekly MET-minutes
  mutate(moderate_met = moderate_weekly_minutes * 5) |> 
  #Transforming observation data to minutes_per_week of vigorous activity
  mutate(vigorous_weekly_minutes = case_when(
    PAD810U == "D" ~ PAD820 * PAD810Q * 7,
    PAD810U == "M" ~ (PAD820 * PAD810Q) / 4,
    PAD810U == "Y" ~ (PAD820 * PAD810Q) / 52,
    PAD810U == "W" ~ PAD820 * PAD810Q )) |> 
  mutate(vigorous_weekly_minutes = round(vigorous_weekly_minutes, digits = 0)) |>
  #Calculating weekly MET-minutes
  mutate(vigorous_met = vigorous_weekly_minutes * 7) |>
  #Summing up MET (vigorous + moderate)
  mutate(weekly_MET = rowSums(pick(moderate_met, vigorous_met), na.rm = TRUE)) |>
  #Summing moderate (* 1) and vigorous (* 2) for WHO guideline equivalency
  mutate(eq_vigorous_weekly_minutes = vigorous_weekly_minutes * 2) |> 
  mutate(who_guideline_total = rowSums(pick(moderate_weekly_minutes, eq_vigorous_weekly_minutes), na.rm = TRUE)
  ) |> 
  #WHO guideline (150 moderate minutes or 75 vigorous minutes or equivalent; yes or no
  mutate(who_guideline = if_else(who_guideline_total >= 150, 1, 0)) |> 
  
  #Smoking data cleaning
  
  #Setting "refused" and "dont know" to NA
  mutate(across(c(SMQ020, SMQ040), ~ replace_values(.x, smoking_refused_or_dunno ~ NA))) |> 
  #
  mutate(smoker = if_else(SMQ020 == 1 &
                            SMQ040 %in% c(1, 2),
                          1, 0)
  ) |> 
  
  #Alcohol use data cleaning
  
  #Setting "refused" and "dont know" to NA
  mutate(across(ALQ111, ~ replace_values(.x, alcohol_small_refused_or_dunno ~ NA))) |> 
  mutate(across(ALQ121, ~ replace_values(.x, alcohol_medium_refused_or_dunno ~ NA))) |> 
  mutate(across(ALQ130, ~ replace_values(.x, alcohol_large_refused_or_dunno ~ NA))) |> 
  #Setting heavy drinker = 2, drinker = 1, non-drinker = 0
  mutate(alcohol_use = case_when(ALQ111 == 1 & Gender == 1 & ALQ130 >= 2 ~ 2,
                                 ALQ111 == 1 & Gender == 1 & ALQ130 == 1 ~ 1,
                                 ALQ111 == 1 & Gender == 0 & ALQ130 >= 1 ~ 2,
                                 ALQ111 == 2 & ALQ121 == 0 ~ 0,
                                 ALQ111 == 2 ~ 0,
                                 .default = 0
                                 )
  ) |> 
  
  
  #Unemployment data cleaning
  
  #Setting OCD150 and OCQ383 "refused" and "dont know" to NA
  mutate(across(OCD150, ~ replace_values(.x, OCD150_refused_or_dunno ~ NA))) |>
  mutate(across(OCQ383, ~ replace_values(.x, OCQ383_refused_or_dunno ~ NA))) |> 
  #Setting employed subjects as 0 and unemployed as 1
  mutate(unemployed = case_when(OCQ383 %in% c(5, 6, 7) ~ 1,
                                OCD150 == 3 ~ 1,
                                .default = 0)
  ) |>
  
  #Diabetes data cleaning
  
  #Setting "refused" and "dont know" to NA
  mutate(across(c(DIQ010, DIQ160, DIQ050, DIQ070), ~ replace_values(.x, diabetes_refused_or_dunno ~ NA))) |> 
  #Changing "No" answer from "2" to "0"
  mutate(across(c(DIQ010, DIQ160, DIQ050, DIQ070), ~ replace_values(.x, 2 ~ 0))) |> 
  #Categorizing diabetess (yes = 1, no = 0) based on if they answered YES to ANY of the questions
  mutate(diabetes = if_else(
    if_any(c(DIQ010, DIQ160, DIQ050, DIQ070), ~ . == 1), 1, 0, missing = 0)) |>
  
  #Blood pressure data cleaning
  
  #Setting "refused" and "dont know" to NA
  mutate(across(BPQ150, ~ replace_values(.x, bpcholesterol_refused_or_dunno ~ NA))) |> 
  #Average systolic and diastolic
  mutate(avg_systolic_bp = round(rowMeans(pick(BPXOSY1, BPXOSY2, BPXOSY3))),
         avg_diastolic_bp = round(rowMeans(pick(BPXODI1, BPXODI2, BPXODI3)))
         ) |> 
  #Defining hypertension
  mutate(hypertension = case_when(avg_systolic_bp >= 130 ~ 1,
                                  avg_diastolic_bp >= 80 ~ 1,
                                  BPQ030 == 1 ~ 1,
                                  BPQ150 == 1 ~ 1,
                                  .default = 0)
  ) |> 
  
  #Cholesterol data cleaning
  
  #Setting "refused" and "dont know" to NA
  mutate(across(c(BPQ080, BPQ101D), ~ replace_values(.x, bpcholesterol_refused_or_dunno ~ NA))) |>
  #Defining dyslipidemia
  mutate(dyslipidemia = if_else(BPQ080 == 1 |
                                  BPQ101D == 1,
                                1, 0)) |> 
  
  #Comorbidities data cleaning
  
  #Setting "refused" and "dont know" to NA
  mutate(across(
    c(MCQ010, MCQ035, MCQ160A, MCQ160B, MCQ160C, MCQ160D, MCQ160E, MCQ160F, MCQ160M, MCQ170M, MCQ160P, MCQ160L, MCQ170L, MCQ220),
    ~ replace_values(.x, comorbidities_refused_or_dunno ~ NA))) |> 
  #Defining other comorbidities
  mutate(asthma = if_else(MCQ010 == 1 & MCQ035 == 1, 1, 0),
         arthritis = if_else(MCQ160A == 1, 1, 0),
         chf = if_else(MCQ160B == 1, 1, 0),
         chd = if_else(MCQ160C == 1, 1, 0),
         angina = if_else(MCQ160D == 1, 1, 0),
         heart_attack = if_else(MCQ160E == 1, 1, 0),
         stroke = if_else(MCQ160F == 1, 1, 0),
         thyroid = if_else(MCQ160M == 1 & MCQ170M == 1, 1, 0),
         copd = if_else(MCQ160P == 1, 1, 0),
         liver_disease = if_else(MCQ160L == 1 & MCQ170L == 1, 1, 0),
         cancer = if_else(MCQ220 == 1, 1, 0)
  ) |> 
  #Defining total comorbidity burden (0, 1 or >=2 comorbidities)
  mutate(comorbidity_total = rowSums(
    pick(
      diabetes, hypertension, dyslipidemia, asthma, arthritis, chf, chd, angina, heart_attack, stroke, thyroid, copd, liver_disease, cancer), na.rm = TRUE)
  ) |> 
  mutate(comorbidity_burden = if_else(comorbidity_total >= 2, 2, comorbidity_total)
  ) |> 


  #Setting main sample

  mutate(main_sample = if_else(
    if_any(DPQ010:DPQ090, is.na) |
      if_all(c(PAD790Q, PAD800, PAD810Q, PAD820), is.na) |
      is.na(sitting_time) |
      if_all(c(SMQ020, SMQ040), is.na) |
      is.na(ALQ111) |
      if_all(c(ALQ111, ALQ121, ALQ130), is.na) |
      if_all(c(diabetes, hypertension, dyslipidemia, asthma, arthritis, chf, chd, angina, heart_attack, stroke, thyroid, copd, liver_disease, cancer), is.na) |
      is.na(OCD150) |
      (OCD150 %in% c(4) & is.na(OCQ383)),
    0, 1)) |> 

  #Removing unnecessary variables

  select(!c(DPQ010:DPQ090)) |>
  select(!starts_with("PAD")) |> 
  select(!c(SMQ020, SMQ040)) |> 
  select(!starts_with("ALQ")) |> 
  select(!c(DIQ010, DIQ160, DIQ050, DIQ070)) |>
  select(!c(BPXOSY1, BPXOSY2, BPXOSY3, BPXODI1, BPXODI2, BPXODI3, 
            avg_systolic_bp, avg_diastolic_bp, BPQ020, BPQ030, BPQ150)) |> 
  select(!c(BPQ080, BPQ101D)) |> 
  select(!starts_with("MCQ")) |> 
  select(!c(OCD150, OCQ383))

view(nhanes_project_2)

```

### Sitting Time

```{r}
#| title: Sitting time tables

library(tidyverse)
library(gt)

#sitting time tables

nhanes_project_2 |> 
  summarize(missing = sum(is.na(sitting_time)),
            proportion_missing = round(mean((is.na(sitting_time))), digits = 2),
            available_data = sum(!is.na(sitting_time)),
            mean = round(mean(sitting_time, na.rm = TRUE), digits = 2),
            sd = round(sd(sitting_time, na.rm = TRUE), digits = 2),
            median = median(sitting_time, na.rm = TRUE),
            iqr = IQR(sitting_time, na.rm = TRUE)
  )|>
  gt() |> 
  tab_header(
    title = md("Sitting time")
  ) |> 
  cols_label(
    missing = md("Missing<br>Data"),
    proportion_missing = md("Proportion <br>Missing <br>Data"),
    available_data = md("Available <br>Data"),
    mean = md("Mean"),
    sd = md("Standard <br>Deviation"),
    median = md("Median"),
    iqr = md("Inter- <br>Quartile <br>Range")
  )

```

```{r}
#| title: Sitting time plots
#| layout-ncol: 2
#| fig-subcap:
#|   - "**Histogram - Minutes of Sitting Time per Day**"
#|   - "**Density Plot - Minutes of Sitting Time per Day**"

library(tidyverse)
library(patchwork)

#sitting time plots

nhanes_project_2 |> 
  ggplot(aes(x = sitting_time)) +
  geom_histogram(binwidth = 120, boundary = 0, fill = "lightgreen") +
  scale_x_continuous(limits = c(0, NA), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

nhanes_project_2 |> 
  ggplot(aes(x = sitting_time)) +
  geom_density(fill = "lightgreen", color = "lightgreen") +
  scale_x_continuous(limits = c(0, NA), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

```

### Physical Activity

```{r}
#| title: Moderate and Vigorous activity tables

library(tidyverse)
library(gt)

#moderate and vigorous

nhanes_project_2 |> 
  summarize(across(c(moderate_weekly_minutes, vigorous_weekly_minutes),
                   list(missing = ~ sum(is.na(.x)),
                        proportion_missing = ~ round(mean(is.na(.x)), digits = 2),
                        available_data = ~ sum(!is.na(.x)),
                        mean = ~ round(mean(.x, na.rm = TRUE), digits = 2),
                        sd = ~ round(sd(.x, na.rm = TRUE), digits = 2),
                        median = ~ round(median(.x, na.rm = TRUE), digits = 2),
                        iqr = ~ IQR(.x, na.rm = TRUE)))
  ) |> 
  gt() |> 
  tab_header(
    title = md("Minutes of Activity per Week")
  ) |> 
  cols_label(ends_with("missing") ~ md("Missing<br>Data"),
             ends_with("proportion_missing") ~ md("Proportion <br>Missing <br>Data"),
             ends_with("available_data") ~md("Available <br>Data"),
             ends_with("mean") ~ md("Mean"),
             ends_with("sd") ~ md("Standard <br>Deviation"),
             ends_with("median") ~ md("Median"),
             ends_with("iqr") ~ md("Inter- <br>Quartile <br>Range")
  ) |> 
  tab_spanner(label = md("**Moderate**"),
              columns = starts_with("moderate")
  ) |> 
  tab_spanner(label = md("**Vigorous**"),
              columns = starts_with("vigorous")
  )

```

```{r}
#| title: Moderate and Vigorous activity Plots
#| layout-ncol: 2
#| fig-subcap: 
#|   - "**Histogram - Weekly minutes of moderate physical activity**"
#|   - "**Density Plot - Weekly minutes of moderate physical activity**"
#|   - "**Histogram - Weekly minutes of vigorous physical activity**"
#|   - "**Density Plot - Weekly minutes of vigorous physical activity**"

#moderate weekly minutes

nhanes_project_2 |> 
  ggplot(aes(x = moderate_weekly_minutes)) +
  geom_histogram(binwidth = 50, boundary = 0, fill = "lightblue") +
  scale_x_continuous(limits = c(0, 4000), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

nhanes_project_2 |> 
  ggplot(aes(x = moderate_weekly_minutes)) +
  geom_density(fill = "lightblue", color = "lightblue") +
  scale_x_continuous(limits = c(0, 4000), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )
#vigorous weekly minutes

nhanes_project_2 |> 
  ggplot(aes(x = vigorous_weekly_minutes)) +
  geom_histogram(binwidth = 50, boundary = 0, fill = "lightblue") +
  scale_x_continuous(limits = c(0, 4000), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

nhanes_project_2 |> 
  ggplot(aes(x = vigorous_weekly_minutes)) +
  geom_density(fill = "lightblue", color = "lightblue") +
  scale_x_continuous(limits = c(0, 4000), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

```

```{r}
#| title: WHO Guideline Tables

#WHO guideline total

nhanes_project_2 |> 
  summarize(who_missing = sum(if_all(c(moderate_weekly_minutes, vigorous_weekly_minutes), is.na)),
            who_proportion_missing = round(mean((if_all(c(moderate_weekly_minutes, vigorous_weekly_minutes), is.na))), digits = 2),
            who_available_data = sum(!if_all(c(moderate_weekly_minutes, vigorous_weekly_minutes), is.na)),
            across(who_guideline_total,
                   list(mean = ~ round(mean(.x, na.rm = TRUE), digits = 2),
                        sd = ~ round(sd(.x, na.rm = TRUE), digits = 2),
                        median = ~ round(median(.x, na.rm = TRUE), digits = 2),
                        iqr = ~ IQR(.x, na.rm = TRUE))),
            who_guideline_met = sum(who_guideline, na.rm = TRUE),
            who_guideline_met_proportion = round(mean(who_guideline, na.rm = TRUE), digits = 2)
            
  ) |> 
  gt() |> 
  tab_header(
    title = md("Minutes of Activity per Week")
  ) |> 
  cols_label(ends_with("missing") ~ md("Missing<br>Data"),
             ends_with("proportion_missing") ~ md("Proportion <br>Missing <br>Data"),
             ends_with("available_data") ~md("Available <br>Data"),
             ends_with("mean") ~ md("Mean"),
             ends_with("sd") ~ md("Standard <br>Deviation"),
             ends_with("median") ~ md("Median"),
             ends_with("iqr") ~ md("Inter- <br>Quartile <br>Range"),
             who_guideline_met ~ md("Guideline <br>Met"),
             who_guideline_met_proportion ~ md("Proportion <br>Guideline <br>Met")
  ) |>  
  tab_spanner(label = md("**WHO <br>Guideline <br>Equivalent**"),
              columns = starts_with("who")
  ) |> 
  tab_footnote(
    footnote = "Total equivalent equals minutes per week of moderate activity + vigorous activity x 2 ",
    locations = cells_column_spanners()
  ) |> 
  tab_footnote(
    footnote = "Participants with total equivalent >= 150 minutes",
    locations = cells_column_labels(
      columns = who_guideline_met
    )
  )


```

```{r}
#| title: WHO Guideline Plots
#| layout-ncol: 2
#| fig-subcap: 
#|   - "**Histogram - Guideline Equivalent Minutes**"
#|   - "**Density Plot - Guideline Equivalent Minutes**"

#WHO guideline total

nhanes_project_2 |> 
  ggplot(aes(x = who_guideline_total)) +
  geom_histogram(binwidth = 50, boundary = 0, fill = "lightblue") +
  scale_x_continuous(limits = c(0, 2000), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

nhanes_project_2 |> 
  ggplot(aes(x = who_guideline_total)) +
  geom_density(fill = "lightblue", color = "lightblue") +
  scale_x_continuous(limits = c(0, 2000), expand = c(0.01, 0.01)) +
  scale_y_continuous(expand = expansion(mult = c(0, 0.05))) +
  xlab(NULL) +
  ylab(NULL) +
  theme_minimal() +
  theme(
    axis.title.x = element_text(size = 15, face = "bold", margin = margin(t = 17)),
    axis.title.y = element_text(size = 15, face = "bold"),
    axis.text.x = element_text(size = 12, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold")
  )

```

### Covariates

#### Demographics

```{r}

#| title: Age, Gender tables

library(tidyverse)
library(gt)

#Demmographics tables

#Age

nhanes_project_2 |> 
  summarize(missing = sum(is.na(Age)),
            proportion_missing = round(mean((is.na(Age))), digits = 2),
            available_data = sum(!is.na(Age)),
            median = median(Age, na.rm = TRUE),
            iqr = IQR(Age, na.rm = TRUE)
  )|>
  gt() |> 
  tab_header(
    title = md("Age")
  ) |> 
  cols_label(
    missing = md("Missing<br>Data"),
    proportion_missing = md("Proportion <br>Missing <br>Data"),
    available_data = md("Available <br>Data"),
    median = md("Median"),
    iqr = md("Inter- <br>Quartile <br>Range")
  ) 

#Gender

nhanes_project_2 |> 
  summarize(missing = sum(is.na(Gender)),
            proportion_missing = round(mean((is.na(Gender))), digits = 2),
            available_data = sum(!is.na(Gender)),
            male = sum(Gender == 1, na.rm = TRUE),
            female = sum(Gender == 0, na.rm = TRUE),
            male_prop = round(mean(Gender == 1, na.rm = TRUE), digits = 3),
            female_prop = round(mean(Gender == 0, na.rm = TRUE), digits = 3)
            
  ) |> 
  gt() |> 
  tab_header(
    title = md("Gender")
  ) |> 
  fmt_percent(
    columns = c(male_prop, female_prop),
    decimals = 2
  ) |> 
  cols_merge_n_pct(
    col_n = male,
    col_pct = male_prop
  ) |> 
  cols_merge_n_pct(
    col_n = female,
    col_pct = female_prop
  ) |> 
  cols_label(
    missing = md("Missing<br>Data"),
    proportion_missing = md("Proportion <br>Missing <br>Data"),
    available_data = md("Available <br>Data"),
    male = md("Male"),
    female = md("Female")
  )

#Race and Ethnicity

#Values for Race 
#(Non-Hispanic White = 0, Mexican American = 1, Other Hispanic  = 2, Non-Hispanic Black = 3,
#Non-Hispanic Asian = 4, Other Race - Including Multi-Racial = 5)


nhanes_project_2 |> 
  group_by(Race) |> 
  summarize(n = n()) |> 
  mutate(proportion =  n / sum(n)) |> 
  pivot_wider(
    names_from = Race,
    values_from = c(n, proportion)
  ) |> 
  
  gt() |> 
  tab_header(
    title = md("Race and Ethnicity")
  ) |> 
  fmt_percent(
    columns = starts_with("proportion"),
    decimals = 1
  ) |> 
  cols_merge_n_pct(
    col_n = n_0,
    col_pct = proportion_0
  ) |> 
  cols_merge_n_pct(
    col_n = n_1,
    col_pct = proportion_1
  ) |> 
  cols_merge_n_pct(
    col_n = n_2,
    col_pct = proportion_2
  ) |> 
  cols_merge_n_pct(
    col_n = n_3,
    col_pct = proportion_3
  ) |> 
  cols_merge_n_pct(
    col_n = n_4,
    col_pct = proportion_4
  ) |> 
  cols_merge_n_pct(
    col_n = n_5,
    col_pct = proportion_5
  ) |> 
  cols_label(
    n_0 = md("Non-Hispanic White"),
    n_1 = md("Mexican American"),
    n_2 = md("Other Hispanic"),
    n_3 = md("Non-Hispanic Black"),
    n_4 = md("Non-Hispanic Asian"),
    n_5 = md("Other Race")
      )
    
    # Ratio income poverty
    
    nhanes_project_2 |> 
      summarize(missing = sum(is.na(Ratio_income_poverty)),
                proportion_missing = round(mean((is.na(Ratio_income_poverty))), digits = 2),
                available_data = sum(!is.na(Ratio_income_poverty)),
                mean = round(mean(Ratio_income_poverty, na.rm = TRUE), digits = 2),
                sd = round(sd(Ratio_income_poverty, na.rm = TRUE), digits = 2),
                median = median(Ratio_income_poverty, na.rm = TRUE),
                iqr = IQR(Ratio_income_poverty, na.rm = TRUE)
      )|>
      gt() |> 
      tab_header(
        title = md("Ratio of family income to poverty")
      ) |> 
      cols_label(
        missing = md("Missing<br>Data"),
        proportion_missing = md("Proportion <br>Missing <br>Data"),
        available_data = md("Available <br>Data"),
        mean = md("Mean"),
        sd = md("Standard <br>Deviation"),
        median = md("Median"),
        iqr = md("Inter- <br>Quartile <br>Range")
      ) |> 
      tab_footnote(
        footnote = "Calculated by dividing total annual family (or individual) income by the poverty guidelines specific to the survey year",
        locations = cells_title()
      ) |> 
      tab_footnote(
        footnote = "Truncated by NHANES at 5.0",
        locations = cells_title()
      ) 
    
    
```
